Railsテキスト教材一覧ページの実装
yanbaru-expert/team_project_53 pull request #38
Opened 2021-07-07 15:52 UTC by kana-o

close #14 

## 実装内容

- `app/models/text.rb` に `RAILS_GENRE_LIST = %w[basic git ruby rails]` を定義
- Railsテキスト教材の一覧ページを作成
  - 表示するジャンルは `Text::RAILS_GENRE_LIST` に制限
  - Bootstrap の `Cards` や `Grid System` を用いてスタイルを設定
  - 画像部分はデフォルト画像を表示  

## 参考資料

- [【公式】Bootstrap Cards](https://getbootstrap.jp/docs/4.5/components/card/)
- [【公式】Bootstrap Grid system](https://getbootstrap.jp/docs/4.5/layout/grid/)

## チェックリスト

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認
- [ ] `rubocop -a` を実行

2021-07-09 06:04 UTC, git-miura approved these changes
LGTMです

2021-07-09 13:34 UTC, great084 requested changes
@kana-o 
画面の表示内容、コードの記載内容概ねOKです。
一点だけ指摘ありますので、確認の上修正願います。

2021-07-09 13:34 UTC, great084 commented on app/views/texts/_text.html.erb
> +      <p>【<%= text.genre %>】</p>
表示するgenreは日本語化したものを表示しましょう。

2021-07-10 05:57 UTC, satoshi07 approved these changes
LGTMです

2021-07-10 10:20 UTC, great084 approved these changes
LGTMです！

2021-07-10 11:42 UTC, merged