動画教材の読破済み機能
yanbaru-expert/team_project_53 pull request #48
Opened 2021-08-03 20:06 UTC by kana-o

close #25 

## 実装内容

- 視聴済み機能に使用する `WatchProgress` モデルを作成
  - `User` モデル，`Movie` モデルと関連付け
  - `user_id`, `movie_id` の組にユニーク制約を入れる

- 動画教材一覧ページに非同期処理の視聴済み機能を実装

## 参考資料（必要があれば）

- [【やんばるエキスパート教材】モデルの関連付け その2（多対多）](https://www.yanbaru-code.com/texts/297)

## チェックリスト

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認
- [ ] `rubocop -a` を実行

2021-08-04 14:47 UTC, great084 reviewed
画面の動作に関しては問題ないです。

動画一覧画面を表示したい際にN+1が発生しているので、よりよいコードにするためには、解消してみてください。(一覧画面表示時の、 rails sever の出力ログ見ると、 以下のSQLが明細分発行されています）
`SELECT 1 AS one FROM "watch_progresses" WHERE "watch_progresses"."movie_id" = $1 AND "watch_progresses"."user_id" = $2 LIMIT $3`

2021-08-05 00:14 UTC, great084 requested changes
動画教材を「視聴済みにする」押下後に「視聴済を解除する」ボタンが表示されるのは良いですが、一覧画面を再表示すると「視聴済みにする」ボタンに戻っており、押下すると、以下のエラーがサーバ側で出力されます
`ActiveRecord::RecordInvalid (バリデーションに失敗しました: Userは同じ動画教材を２回以上視聴済みにはできません):`


参考までにN+1解消のためのわかりやすい記事を掲載しておきます。
https://pikawaka.com/rails/includes

2021-08-05 00:14 UTC, great084 commented on app/models/movie.rb
> +    watch_progresses.where(user_id: user.id)
この条件部分は修正前の`exists?`であるべきです。
修正前の`exists?`だと、true/falseが返っていましたが、 `where`の場合データが 空でもオブジェクトを返すため、全てtrueになったしまいます。

2021-08-07 00:31 UTC, great084 approved these changes

2021-08-07 00:32 UTC, great084 commented
@kana-o 
LGTMです！

2021-08-07 12:27 UTC, git-miura approved these changes
LGTMです。一連のN+1問題解決について、大変勉強になりました。

2021-08-08 10:40 UTC, satoshi07 approved these changes
LGTMです

2021-08-08 14:15 UTC, merged